
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

   <div>
        <p>CHAT</p>
        <div>
            <?php foreach($data as $val): ?>
                <p><?= $val["message"] ?> </p>
            <?php endforeach; ?>
        </div>
   </div>
    
</body>
</html>